ARG NODE_VERSION=16

FROM node:${NODE_VERSION} AS base

FROM base AS client
COPY packages/client /home/client/
WORKDIR /home/client
RUN yarn install --frozen-lockfile && yarn build

FROM base AS server
COPY packages/server /home/server/

WORKDIR /home/server
RUN yarn install --frozen-lockfile
COPY --from=client /home/client/ ./node_modules/client
RUN rm -rf /home/server/dist/ && yarn build

CMD ["node", "/home/server/dist/index.js"]

EXPOSE ${SERVER_PORT}
