ARG NODE_VERSION=16

FROM node:${NODE_VERSION}

COPY ./packages/server /home/server

WORKDIR /home/server

RUN yarn install --frozen-lockfile
RUN yarn build

EXPOSE ${SERVER_PORT}
CMD [ "node", "/home/server/dist/index.js" ]
