ARG NODE_VERSION=16

FROM node:$NODE_VERSION as base

WORKDIR /app
FROM base as builder
COPY packages/client ./
RUN yarn install --frozen-lockfile && yarn build

FROM nginx:latest as production
WORKDIR /app
COPY --from=builder /app/dist/ /app/
COPY --from=builder /app/nginx.conf /etc/nginx/nginx.conf
RUN ls /app

EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
